/**
 * Municipios de cada departamento de Guatemala salvo Alta Verapaz (ese tiene su propio catálogo
 * con claves, `MUNICIPIOS_ALTA_VERAPAZ`, porque es la región que se atiende y se reporta aparte).
 *
 * Se guardan como texto en `Usuaria.municipioOtro`, así que el nombre exacto de esta lista es el
 * valor canónico: los reportes agrupan por él. Nombres según el INE (340 municipios en total,
 * 323 aquí + 17 de Alta Verapaz). Si se crea un municipio nuevo, se agrega aquí; mientras tanto
 * Trabajo Social puede escribirlo a mano con la opción "Otro".
 */
export const MUNICIPIOS_POR_DEPARTAMENTO = {
  Guatemala: [
    'Guatemala',
    'Santa Catarina Pinula',
    'San José Pinula',
    'San José del Golfo',
    'Palencia',
    'Chinautla',
    'San Pedro Ayampuc',
    'Mixco',
    'San Pedro Sacatepéquez',
    'San Juan Sacatepéquez',
    'San Raymundo',
    'Chuarrancho',
    'Fraijanes',
    'Amatitlán',
    'Villa Nueva',
    'Villa Canales',
    'San Miguel Petapa',
  ],
  'El Progreso': [
    'Guastatoya',
    'Morazán',
    'San Agustín Acasaguastlán',
    'San Cristóbal Acasaguastlán',
    'El Jícaro',
    'Sansare',
    'Sanarate',
    'San Antonio La Paz',
  ],
  Sacatepéquez: [
    'Antigua Guatemala',
    'Jocotenango',
    'Pastores',
    'Sumpango',
    'Santo Domingo Xenacoj',
    'Santiago Sacatepéquez',
    'San Bartolomé Milpas Altas',
    'San Lucas Sacatepéquez',
    'Santa Lucía Milpas Altas',
    'Magdalena Milpas Altas',
    'Santa María de Jesús',
    'Ciudad Vieja',
    'San Miguel Dueñas',
    'Alotenango',
    'San Antonio Aguas Calientes',
    'Santa Catarina Barahona',
  ],
  Chimaltenango: [
    'Chimaltenango',
    'San José Poaquil',
    'San Martín Jilotepeque',
    'Comalapa',
    'Santa Apolonia',
    'Tecpán Guatemala',
    'Patzún',
    'Pochuta',
    'Patzicía',
    'Santa Cruz Balanyá',
    'Acatenango',
    'Yepocapa',
    'San Andrés Itzapa',
    'Parramos',
    'Zaragoza',
    'El Tejar',
  ],
  Escuintla: [
    'Escuintla',
    'Santa Lucía Cotzumalguapa',
    'La Democracia',
    'Siquinalá',
    'Masagua',
    'Tiquisate',
    'La Gomera',
    'Guanagazapa',
    'San José',
    'Iztapa',
    'Palín',
    'San Vicente Pacaya',
    'Nueva Concepción',
    'Sipacate',
  ],
  'Santa Rosa': [
    'Cuilapa',
    'Barberena',
    'Santa Rosa de Lima',
    'Casillas',
    'San Rafael Las Flores',
    'Oratorio',
    'San Juan Tecuaco',
    'Chiquimulilla',
    'Taxisco',
    'Santa María Ixhuatán',
    'Guazacapán',
    'Santa Cruz Naranjo',
    'Pueblo Nuevo Viñas',
    'Nueva Santa Rosa',
  ],
  Sololá: [
    'Sololá',
    'San José Chacayá',
    'Santa María Visitación',
    'Santa Lucía Utatlán',
    'Nahualá',
    'Santa Catarina Ixtahuacán',
    'Santa Clara La Laguna',
    'Concepción',
    'San Andrés Semetabaj',
    'Panajachel',
    'Santa Catarina Palopó',
    'San Antonio Palopó',
    'San Lucas Tolimán',
    'Santa Cruz La Laguna',
    'San Pablo La Laguna',
    'San Marcos La Laguna',
    'San Juan La Laguna',
    'San Pedro La Laguna',
    'Santiago Atitlán',
  ],
  Totonicapán: [
    'Totonicapán',
    'San Cristóbal Totonicapán',
    'San Francisco El Alto',
    'San Andrés Xecul',
    'Momostenango',
    'Santa María Chiquimula',
    'Santa Lucía La Reforma',
    'San Bartolo',
  ],
  Quetzaltenango: [
    'Quetzaltenango',
    'Salcajá',
    'Olintepeque',
    'San Carlos Sija',
    'Sibilia',
    'Cabricán',
    'Cajolá',
    'San Miguel Sigüilá',
    'San Juan Ostuncalco',
    'San Mateo',
    'Concepción Chiquirichapa',
    'San Martín Sacatepéquez',
    'Almolonga',
    'Cantel',
    'Huitán',
    'Zunil',
    'Colomba Costa Cuca',
    'San Francisco La Unión',
    'El Palmar',
    'Coatepeque',
    'Génova',
    'Flores Costa Cuca',
    'La Esperanza',
    'Palestina de Los Altos',
  ],
  Suchitepéquez: [
    'Mazatenango',
    'Cuyotenango',
    'San Francisco Zapotitlán',
    'San Bernardino',
    'San José El Ídolo',
    'Santo Domingo Suchitepéquez',
    'San Lorenzo',
    'Samayac',
    'San Pablo Jocopilas',
    'San Antonio Suchitepéquez',
    'San Miguel Panán',
    'San Gabriel',
    'Chicacao',
    'Patulul',
    'Santa Bárbara',
    'San Juan Bautista',
    'Santo Tomás La Unión',
    'Zunilito',
    'Pueblo Nuevo',
    'Río Bravo',
    'San José La Máquina',
  ],
  Retalhuleu: [
    'Retalhuleu',
    'San Sebastián',
    'Santa Cruz Muluá',
    'San Martín Zapotitlán',
    'San Felipe',
    'San Andrés Villa Seca',
    'Champerico',
    'Nuevo San Carlos',
    'El Asintal',
  ],
  'San Marcos': [
    'San Marcos',
    'San Pedro Sacatepéquez',
    'San Antonio Sacatepéquez',
    'Comitancillo',
    'San Miguel Ixtahuacán',
    'Concepción Tutuapa',
    'Tacaná',
    'Sibinal',
    'Tajumulco',
    'Tejutla',
    'San Rafael Pie de la Cuesta',
    'Nuevo Progreso',
    'El Tumbador',
    'El Rodeo',
    'Malacatán',
    'Catarina',
    'Ayutla',
    'Ocós',
    'San Pablo',
    'El Quetzal',
    'La Reforma',
    'Pajapita',
    'Ixchiguán',
    'San José Ojetenam',
    'San Cristóbal Cucho',
    'Sipacapa',
    'Esquipulas Palo Gordo',
    'Río Blanco',
    'San Lorenzo',
    'La Blanca',
  ],
  Huehuetenango: [
    'Huehuetenango',
    'Chiantla',
    'Malacatancito',
    'Cuilco',
    'Nentón',
    'San Pedro Necta',
    'Jacaltenango',
    'Soloma',
    'San Ildefonso Ixtahuacán',
    'Santa Bárbara',
    'La Libertad',
    'La Democracia',
    'San Miguel Acatán',
    'San Rafael La Independencia',
    'Todos Santos Cuchumatán',
    'San Juan Atitán',
    'Santa Eulalia',
    'San Mateo Ixtatán',
    'Colotenango',
    'San Sebastián Huehuetenango',
    'Tectitán',
    'Concepción Huista',
    'San Juan Ixcoy',
    'San Antonio Huista',
    'San Sebastián Coatán',
    'Barillas',
    'Aguacatán',
    'San Rafael Petzal',
    'San Gaspar Ixchil',
    'Santiago Chimaltenango',
    'Santa Ana Huista',
    'Unión Cantinil',
    'Petatán',
  ],
  Quiché: [
    'Santa Cruz del Quiché',
    'Chiché',
    'Chinique',
    'Zacualpa',
    'Chajul',
    'Chichicastenango',
    'Patzité',
    'San Antonio Ilotenango',
    'San Pedro Jocopilas',
    'Cunén',
    'San Juan Cotzal',
    'Joyabaj',
    'Nebaj',
    'San Andrés Sajcabajá',
    'Uspantán',
    'Sacapulas',
    'San Bartolomé Jocotenango',
    'Canillá',
    'Chicamán',
    'Ixcán',
    'Pachalum',
  ],
  'Baja Verapaz': [
    'Salamá',
    'San Miguel Chicaj',
    'Rabinal',
    'Cubulco',
    'Granados',
    'El Chol',
    'San Jerónimo',
    'Purulhá',
  ],
  Petén: [
    'Flores',
    'San José',
    'San Benito',
    'San Andrés',
    'La Libertad',
    'San Francisco',
    'Santa Ana',
    'Dolores',
    'San Luis',
    'Sayaxché',
    'Melchor de Mencos',
    'Poptún',
    'Las Cruces',
    'El Chal',
  ],
  Izabal: ['Puerto Barrios', 'Livingston', 'El Estor', 'Morales', 'Los Amates'],
  Zacapa: [
    'Zacapa',
    'Estanzuela',
    'Río Hondo',
    'Gualán',
    'Teculután',
    'Usumatlán',
    'Cabañas',
    'San Diego',
    'La Unión',
    'Huité',
    'San Jorge',
  ],
  Chiquimula: [
    'Chiquimula',
    'San José La Arada',
    'San Juan Ermita',
    'Jocotán',
    'Camotán',
    'Olopa',
    'Esquipulas',
    'Concepción Las Minas',
    'Quezaltepeque',
    'San Jacinto',
    'Ipala',
  ],
  Jalapa: [
    'Jalapa',
    'San Pedro Pinula',
    'San Luis Jilotepeque',
    'San Manuel Chaparrón',
    'San Carlos Alzatate',
    'Monjas',
    'Mataquescuintla',
  ],
  Jutiapa: [
    'Jutiapa',
    'El Progreso',
    'Santa Catarina Mita',
    'Agua Blanca',
    'Asunción Mita',
    'Yupiltepeque',
    'Atescatempa',
    'Jerez',
    'El Adelanto',
    'Zapotitlán',
    'Comapa',
    'Jalpatagua',
    'Conguaco',
    'Moyuta',
    'Pasaco',
    'San José Acatempa',
    'Quesada',
  ],
} as const satisfies Record<string, readonly string[]>

export type DepartamentoFueraAltaVerapaz = keyof typeof MUNICIPIOS_POR_DEPARTAMENTO

/**
 * Forma de comparar nombres escritos a mano contra el catálogo: sin tildes, sin mayúsculas y
 * sin espacios de más ("  san josé " y "San Jose" son el mismo municipio).
 */
export function normalizarNombreLugar(texto: string): string {
  return normalizarEspacios(texto.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase())
}

/** Un solo espacio entre palabras y ninguno en los extremos: así se guarda un municipio escrito a mano. */
export function normalizarEspacios(texto: string): string {
  return texto.replace(/\s+/g, ' ').trim()
}

/** Municipios del departamento, o una lista vacía si el departamento no es uno de fuera de Alta Verapaz. */
export function municipiosDeDepartamento(departamento: string): readonly string[] {
  return Object.hasOwn(MUNICIPIOS_POR_DEPARTAMENTO, departamento)
    ? MUNICIPIOS_POR_DEPARTAMENTO[departamento as DepartamentoFueraAltaVerapaz]
    : []
}

/**
 * Nombre del catálogo al que equivale un texto escrito a mano (ignorando tildes y mayúsculas),
 * o `null` si no está en la lista de ese departamento.
 */
export function municipioDelCatalogo(departamento: string, texto: string): string | null {
  const buscado = normalizarNombreLugar(texto)
  return municipiosDeDepartamento(departamento).find((m) => normalizarNombreLugar(m) === buscado) ?? null
}
